title: "DaMaLOS 2023 @ ESWC"
remote_theme: pmarsceill/just-the-docs
logo: ./damalos2023.gif
search_enabled: false
aux_links:
  "Home": "../index"
footer_content: "email: damalos2023@easychair.org | Follow us on Twitter and Mastodon #DaMaLOS2023"


description: "DaMaLOS 2023 @ ESWC"
github_username:  ljgarcia
email: ljgarcia@zbmed.de

