title: "DaMaLOS 2025 @ ESWC"
remote_theme: pmarsceill/just-the-docs
logo: ./damalos2025.gif
search_enabled: false
aux_links:
  "Home": "../index"
footer_content: "email: mara-damalos-airdem@googlegroups.com | Follow us on Fostodon/Mastodon #DaMaLOS2025"


description: "DaMaLOS 2025 @ ESWC"
github_username: ljgarcia
email: ljgarcia@zbmed.de

