title: "DaMaLOS 2022 @ ISWC"
remote_theme: pmarsceill/just-the-docs
logo: ./damalos.gif
search_enabled: false
aux_links:
  "Home": "../index"
footer_content: "email: damalos2022@easychair.org | Follow us on twitter @ZB_MED @UniCologne #damalos2022"


description: "DaMaLOS 2022 @ ISWC"
twitter_username: zb_med
github_username:  ljgarcia
email: ljgarcia@zbmed.de

