title: "DaMaLOS 2024 @ ESWC"
remote_theme: pmarsceill/just-the-docs
logo: ./damalos2024.gif
search_enabled: false
aux_links:
  "Home": "../index"
footer_content: "email: damalos2024@easychair.org | Follow us on Fostodon/Mastodon and Twitter #DaMaLOS2024"


description: "DaMaLOS 2024 @ ESWC"
github_username:  ljgarcia
email: ljgarcia@zbmed.de

