title: "DaMaLOS"
remote_theme: pmarsceill/just-the-docs
logo: ./damalos.gif
search_enabled: false
aux_links:
  "Home": "../index"
footer_content: "email: damalos2020@easychair.org | Follow us on twitter @ZB_MED #damalos2020"


description: "First ISWC co-located workshop on Research data management for Linked Open Science - DaMaLOS 2020"
twitter_username: zb_med
github_username:  ljgarcia
email: ljgarcia@zbmed.de

